In [3]:
# Importing
import pandas as pd
import numpy as np
from utils.fake_na_detection_and_cleaning import detect_fake_nulls,replace_fake_nulls
from utils.sql_connector import connect_sql,read_sql_query,write_to_sql
from utils.data_type_converter import string_to_category,string_to_numeric
from utils.normalizer import normalize_categorical_columns_exploding,normalize_categorical_columns_manual_mapping,normalize_na_replacer_columns,normalize_categorical_columns_non_exploding,clean_years_columns,fill_na_and_remove_outlier_percentaile_method

In [4]:
# loading of 2021 datasets
query='select * from Bronze.Survey_2021'
database='Stack_Overflow_Survey'
conn, engine = connect_sql('Stack_Overflow_Survey')
Survey_2021_df = read_sql_query(query, conn)

Successfully Connected
<pyodbc.Connection object at 0x000002F65B616DB0>

c:\Users\Ayush\Git Repo\Stack-Over-Flow-Survey-Data-Engineering-Project\Data Warehouse\Silver Layer\utils\sql_connector.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

Query executed successfully

In [18]:
Survey_2021_df_cleaned=Survey_2021_df.copy()
detect_fake_nulls(Survey_2021_df_cleaned)
replace_fake_nulls(Survey_2021_df_cleaned)

categorical_cols = [
    "MainBranch", "Employment", "EdLevel", "Age", "Age1stCode",
    "LearnCode", "OpSys", "OrgSize", "Country", "US_State", "UK_Country",
    "Gender", "Trans", "Sexuality", "Ethnicity", "Accessibility",
    "MentalHealth", "SOVisitFreq", "SOAccount", "SOPartFreq", "SOComm",
    "NEWSOSites", "NEWOtherComms", "NEWStuck", "CompFreq",
    "SurveyLength", "SurveyEase", "DevType"
]

{'Accessibility': {'NA': np.int64(5836)},
 'Age': {'NA': np.int64(1032)},
 'Age1stCode': {'NA': np.int64(196)},
 'CompFreq': {'NA': np.int64(31289)},
 'CompTotal': {'NA': np.int64(36256)},
 'ConvertedCompYearly': {'NA': np.int64(36595)},
 'Currency': {'NA': np.int64(22359)},
 'DatabaseHaveWorkedWith': {'NA': np.int64(13893)},
 'DatabaseWantToWorkWith': {'NA': np.int64(25140)},
 'DevType': {'NA': np.int64(16955)},
 'EdLevel': {'NA': np.int64(313)},
 'Employment': {'NA': np.int64(116)},
 'Ethnicity': {'NA': np.int64(3975)},
 'Gender': {'NA': np.int64(1153)},
 'LanguageHaveWorkedWith': {'NA': np.int64(1082)},
 'LanguageWantToWorkWith': {'NA': np.int64(6618)},
 'LearnCode': {'NA': np.int64(476)},
 'MentalHealth': {'NA': np.int64(6519)},
 'MiscTechHaveWorkedWith': {'NA': np.int64(36384)},
 'MiscTechWantToWorkWith': {'NA': np.int64(45418)},
 'NEWCollabToolsHaveWorkedWith': {'NA': np.int64(2205)},
 'NEWCollabToolsWantToWorkWith': {'NA': np.int64(10417)},
 'NEWOtherComms': {'NA': np.int64(611)},
 'NEWSOSites': {'NA': np.int64(268)},
 'NEWStuck': {'NA': np.int64(387)},
 'OpSys': {'NA': np.int64(145)},
 'OrgSize': {'NA': np.int64(22713)},
 'PlatformHaveWorkedWith': {'NA': np.int64(31304)},
 'PlatformWantToWorkWith': {'NA': np.int64(41820)},
 'SOAccount': {'NA': np.int64(914)},
 'SOComm': {'NA': np.int64(1120)},
 'SOPartFreq': {'NA': np.int64(15886)},
 'SOVisitFreq': {'NA': np.int64(1026)},
 'Sexuality': {'NA': np.int64(10073)},
 'SurveyEase': {'NA': np.int64(1491)},
 'SurveyLength': {'NA': np.int64(1728)},
 'ToolsTechHaveWorkedWith': {'NA': np.int64(10902)},
 'ToolsTechWantToWorkWith': {'NA': np.int64(17959)},
 'Trans': {'NA': np.int64(2761)},
 'UK_Country': {'NA': np.int64(79021)},
 'US_State': {'NA': np.int64(68519)},
 'WebframeHaveWorkedWith': {'NA': np.int64(21732)},
 'WebframeWantToWorkWith': {'NA': np.int64(31344)},
 'YearsCode': {'NA': np.int64(1798)},
 'YearsCodePro': {'NA': np.int64(22223)}}

In [19]:
# Mormalization of categorical columns : Basic mapping of values to reduce the number of unique values in each column and make it more consistent for analysis and visualization.

employment_map = {
    'Employed full-time': 'Employed',
    'Employed part-time': 'Employed',
    'Independent contractor, freelancer, or self-employed': 'Freelance',
    'Student, full-time': 'Student',
    'Student, part-time': 'Student',
    'Not employed, but looking for work': 'Unemployed',
    'Not employed, and not looking for work': 'Unemployed',
    'Retired': 'Retired',
    'I prefer not to say': 'I prefer not to say',
    'Nan' : 'Not Available',
}
ed_level_map = {
    'BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)': 'Undergraduate',
    'MasterΓÇÖs degree (M.A., M.S., M.Eng., MBA, etc.)': 'Postgraduate',
    'Some college/university study without earning a degree': 'Undergraduate',
    'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)': 'High School',
    'Other doctoral degree (Ph.D., Ed.D., etc.)': 'Doctorate',
    'Primary/elementary school': 'Primary',
    'Associate degree (A.A., A.S., etc.)': 'Undergraduate',
    'Something else': 'Other',
    'Professional degree (JD, MD, etc.)': 'Postgraduate'
}
age_1st_code_map = {
    'Younger than 5 years': '<5',
    '5 - 10 years': '5-10',
    '11 - 17 years': '11-17',
    '18 - 24 years': '18-24',
    '25 - 34 years': '25-34',
    '35 - 44 years': '35-44',
    '45 - 54 years': '45-54',
    '55 - 64 years': '55-64',
    'Older than 64 years': '>64'
}
age_map = {
    'Under 18 years old': 'less than 18',
    '18-24 years old': '18-24',
    '25-34 years old': '25-34',
    '35-44 years old': '35-44',
    '45-54 years old': '45-54',
    '55-64 years old': '55-64',
    '65 years or older': 'greater than65',
    'Prefer not to say': 'Unknown'
}
operating_system_map = {
    'Windows Subsystem for Linux (WSL)': 'WSL',
    'Linux-based': 'Linux',
    'MacOS': 'MacOS',
    'Windows': 'Windows',
    'BSD': 'Unix/BSD',
    'Other (please specify):': 'Other'
}
org_mapping = {
    'Just me - I am a freelancer, sole proprietor, etc.': 'Self-employed',
    '2 to 9 employees': 'Micro (2-9)',
    '10 to 19 employees': 'Small (10-19)',
    '20 to 99 employees': 'Small-Medium (20-99)',
    '100 to 499 employees': 'Medium (100-499)',
    '500 to 999 employees': 'Large (500-999)',
    '1,000 to 4,999 employees': 'Enterprise (1K-4.9K)',
    '5,000 to 9,999 employees': 'Enterprise (5K-9.9K)',
    '10,000 or more employees': 'Enterprise (10K+)'
}

trans_map = {
    'No': 'No',
    'Yes': 'Yes',
    'Prefer not to say': 'Unknown',
    'Or, in your own words:': 'Self-described'
}
visit_freq_map = {
    'Multiple times per day': 'High (Multiple/Day)',
    'Daily or almost daily': 'High (Daily)',
    'A few times per week': 'Medium (Weekly)',
    'A few times per month or weekly': 'Medium (Monthly/Weekly)',
    'Less than once per month or monthly': 'Low (Monthly)',
}
so_account_map = {
    'Yes': 'Yes',
    'No': 'No',
    '''Not sure/can't remember''': 'Uncertain',
}
part_freq_map = {
    'Multiple times per day': 'High (Multiple/Day)',
    'Daily or almost daily': 'High (Daily)',
    'A few times per week': 'Medium (Weekly)',
    'A few times per month or weekly': 'Medium (Monthly/Weekly)',
    'Less than once per month or monthly': 'Low (Monthly)',
    'I have never participated in Q&A on Stack Overflow': 'Never'
}
comm_map = {
    'Yes, definitely': 'Strongly Positive',
    'Yes, somewhat': 'Positive',
    'Neutral': 'Neutral',
    'No, not really': 'Negative',
    'No, not at all': 'Strongly Negative',
    'Not sure': 'Uncertain'
}
new_so_sites_map = {
    'Stack Overflow;Stack Exchange': 'SO & Stack Exchange',
    'Stack Overflow': 'Stack Overflow Only',
    'Stack Overflow;Stack Exchange;Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies)': 'Full Network User',
    'I have never visited Stack Overflow or the Stack Exchange network': 'Never Visited',
    'Stack Overflow;Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies)': 'SO & Teams',
    'Stack Exchange': 'Stack Exchange Only',
    'Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies)': 'Teams Only',
    'Stack Exchange;Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies)': 'SE & Teams'
}
survey_length_map = {
    'Appropriate in length': 'Appropriate',
    'Too long': 'Too Long',
    'Too short': 'Too Short'
}
survey_ease_map = {
    'Easy': 'Easy',
    'Neither easy nor difficult': 'Neutral',
    'Difficult': 'Difficult'
}
un_normalized_cols_name = [
    'Employment', 'EdLevel', 'Age', 'Age1stCode', 'OpSys', 'OrgSize', 'Trans', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOComm', 'NEWSOSites', 'SurveyLength', 'SurveyEase'
]
normalized_cols_name=[
    'Employment','Education_Level','Age','AgeCode','OperatingSystem','Organization_Size',"TransGender","StackOverflow_Visit_Frequency","StackOverflow_Account_exists","StackOverflow_Participation_Frequency","StackOverflow_Community_Experience","NewStackOverflow_Sites",'Survey_Length','Survey_Ease'
]
columns_map=[
    employment_map, ed_level_map, age_map, age_1st_code_map, operating_system_map,org_mapping, trans_map, visit_freq_map, so_account_map, part_freq_map, comm_map, new_so_sites_map, survey_length_map, survey_ease_map
]

Survey_2021_df_cleaned = normalize_categorical_columns_manual_mapping(Survey_2021_df_cleaned, un_normalized_cols_name, normalized_cols_name, columns_map)

['Independent contractor, freelancer, or self-employed'
 'Student, full-time' 'Employed full-time' 'Student, part-time'
 'I prefer not to say' 'Employed part-time'
 'Not employed, but looking for work' 'Retired'
 'Not employed, and not looking for work' nan]
Employment
Employed                       56045
Student                        13832
Freelance                       8041
Unemployed                      4189
I prefer not to say              890
Retired                          326
Not Available or Applicable      116
Name: count, dtype: int64
['Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)'
 'BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)'
 'MasterΓÇÖs degree (M.A., M.S., M.Eng., MBA, etc.)'
 'Other doctoral degree (Ph.D., Ed.D., etc.)'
 'Some college/university study without earning a degree' 'Something else'
 'Professional degree (JD, MD, etc.)' 'Primary/elementary school'
 'Associate degree (A.A., A.S., etc.)' nan]
Education_Level
Undergraduate                  48177
Postgraduate                   18768
High School                     9534
Doctorate                       2567
Primary                         2479
Other                           1601
Not Available or Applicable      313
Name: count, dtype: int64
['25-34 years old' '18-24 years old' '35-44 years old' 'Prefer not to say'
 '45-54 years old' 'Under 18 years old' '65 years or older'
 '55-64 years old' nan]
Age
25-34                          32568
18-24                          20993
35-44                          15183
45-54                           5472
less than 18                    5376
55-64                           1819
Not Available or Applicable     1032
Unknown                          575
greater than65                   421
Name: count, dtype: int64
['18 - 24 years' '11 - 17 years' '5 - 10 years' '25 - 34 years'
 '35 - 44 years' 'Younger than 5 years' '45 - 54 years' '55 - 64 years'
 nan 'Older than 64 years']
AgeCode
11-17                          44170
18-24                          20065
5-10                           11720
25-34                           4199
35-44                           1312
<5                               905
45-54                            544
55-64                            245
Not Available or Applicable      196
>64                               83
Name: count, dtype: int64
['MacOS' 'Windows' 'Linux-based' 'BSD' 'Other (please specify):' nan
 'Windows Subsystem for Linux (WSL)']
OperatingSystem
Windows                        37758
Linux                          21088
MacOS                          20984
WSL                             2743
Other                            575
Unix/BSD                         146
Not Available or Applicable      145
Name: count, dtype: int64
['20 to 99 employees' nan '100 to 499 employees'
 'Just me - I am a freelancer, sole proprietor, etc.'
 '10,000 or more employees' '10 to 19 employees'
 '1,000 to 4,999 employees' '500 to 999 employees'
 '5,000 to 9,999 employees' '2 to 9 employees' 'I donΓÇÖt know']
Organization_Size
Not Available or Applicable    24067
Small-Medium (20-99)           12507
Medium (100-499)               10506
Enterprise (10K+)               8016
Micro (2-9)                     6551
Enterprise (1K-4.9K)            6287
Small (10-19)                   5404
Self-employed                   4033
Large (500-999)                 3789
Enterprise (5K-9.9K)            2279
Name: count, dtype: int64
['No' 'Prefer not to say' 'Yes' nan 'Or, in your own words:']
TransGender
No                             77275
Not Available or Applicable     2761
Unknown                         1764
Yes                             1035
Self-described                   604
Name: count, dtype: int64
['Multiple times per day' 'Daily or almost daily' 'A few times per week'
 'A few times per month or weekly' nan
 'Less than once per month or monthly']
StackOverflow_Visit_Frequency
High (Daily)                   25262
Medium (Weekly)                22481
High (Multiple/Day)            19580
Medium (Monthly/Weekly)        12710
Low (Monthly)                   2380
Not Available or Applicable     1026
Name: count, dtype: int64
['Yes' "Not sure/can't remember" 'No' nan]
StackOverflow_Account_exists
Yes                            67813
No                             10510
Uncertain                       4202
Not Available or Applicable      914
Name: count, dtype: int64
['A few times per month or weekly' 'Daily or almost daily'
 'Multiple times per day' 'A few times per week'
 'I have never participated in Q&A on Stack Overflow'
 'Less than once per month or monthly' nan]
StackOverflow_Participation_Frequency
Low (Monthly)                  30778
Not Available or Applicable    15886
Never                          14243
Medium (Monthly/Weekly)        12978
Medium (Weekly)                 5687
High (Daily)                    2613
High (Multiple/Day)             1254
Name: count, dtype: int64
['Yes, definitely' 'Neutral' 'Yes, somewhat' 'No, not at all'
 'No, not really' nan 'Not sure']
StackOverflow_Community_Experience
Positive                       23584
Negative                       20697
Neutral                        17084
Strongly Positive              12888
Strongly Negative               6633
Uncertain                       1433
Not Available or Applicable     1120
Name: count, dtype: int64
['Stack Overflow' 'Stack Overflow;Stack Exchange'
 'Stack Overflow;Stack Exchange;Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies)'
 nan 'Stack Exchange'
 'Stack Overflow;Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies)'
 'Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies)'
 'I have never visited Stack Overflow or the Stack Exchange network'
 'Stack Exchange;Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies)']
NewStackOverflow_Sites
SO & Stack Exchange            54658
Stack Overflow Only            23473
Full Network User               3099
Never Visited                    750
SO & Teams                       671
Not Available or Applicable      268
Stack Exchange Only              257
Teams Only                       246
SE & Teams                        17
Name: count, dtype: int64
['Appropriate in length' 'Too long' nan 'Too short']
Survey_Length
Appropriate                    64514
Too Long                       13087
Too Short                       4110
Not Available or Applicable     1728
Name: count, dtype: int64
['Easy' 'Neither easy nor difficult' nan 'Difficult']
Survey_Ease
Easy                           63087
Neutral                        18091
Not Available or Applicable     1491
Difficult                        770
Name: count, dtype: int64

In [20]:
# Mormalization of categorical columns : changing NA to more meaningful values and make it more consistent for analysis and visualization.

nan_replacer_columns=[
    'US_State', 'UK_Country', 'NEWOtherComms','CompFreq'
    ]
cleaned_nan_replacer_columns=[
    'USA_State', 'UK_Country', 'Know_Other_Community','Compensation_Frequency'
]
Survey_2021_df_cleaned=normalize_na_replacer_columns(Survey_2021_df_cleaned,nan_replacer_columns, cleaned_nan_replacer_columns)

In [21]:
# Mormalization of categorical columns : Multi-select columns where respondents could select multiple options, resulting in semicolon-separated values. We will map the individual options to broader categories and also create a new category for respondents who selected multiple options.

gender_map = {
    'Man': 'Man',
    'Woman': 'Woman',
    'Non-binary, genderqueer, or gender non-conforming': 'Non-binary / GNC',
    'Prefer not to say': 'Unknown',
    'Or, in your own words:': 'Non-binary / GNC',
}
ethnicity_map = {
    'White or of European descent': 'White',
    'South Asian': 'South Asian',
    'Middle Eastern': 'Middle Eastern',
    'Southeast Asian': 'Southeast Asian',
    'East Asian': 'East Asian',
    'Hispanic or Latino/a/x': 'Hispanic/Latino',
    'Black or of African descent': 'Black',
    'Indigenous (such as Native American, Pacific Islander, or Indigenous Australian)': 'Indigenous',
    'Multiracial': 'Multiracial/Biracial',
    'Biracial': 'Multiracial/Biracial',
    'Or, in your own words:': 'Self-described',
    'Prefer not to say': 'Unknown',
    "I don't know": 'Unknown'
}
learn_code_map = {
    'School': 'Academic (Degree)',
    'Coding Bootcamp': 'Bootcamp',
    'Online Courses or Certification': 'Online Certifications',
    'Other online resources (ex: videos, blogs, etc)': 'Digital Self-Taught',
    'Books / Physical media': 'Physical Media',
    'Online Forum': 'Community/Forums',
    'Colleague': 'Professional Network',
    'Friend or family member': 'Social/Family',
    'Other (please specify):': 'Other'
}
sexuality_map = {
    'Straight / Heterosexual': 'Straight',
    'Bisexual': 'Bisexual',
    'Gay or Lesbian': 'Gay or Lesbian',
    'Queer': 'Queer',
    'Prefer to self-describe:': 'Self-described',
    'Prefer not to say': 'Unknown'
}
accessibility_map = {
    'None of the above': 'None',
    'I am deaf / hard of hearing': 'Hearing Impairment',
    'I am blind / have difficulty seeing': 'Visual Impairment',
    'I am unable to / find it difficult to type': 'Mobility (Typing)',
    'I am unable to / find it difficult to walk or stand without assistance': 'Mobility (Walking/Standing)',
    'Or, in your own words:': 'Self-described',
    'Prefer not to say': 'Unknown'
}
mental_health_map = {
    'None of the above': 'None',
    'I have a concentration and/or memory disorder (e.g. ADHD)': 'ADHD/Concentration',
    'I have an anxiety disorder': 'Anxiety',
    'I have a mood or emotional disorder (e.g. depression, bipolar disorder)': 'Mood/Emotional',
    "I have autism / an autism spectrum disorder (e.g. Asperger's)": 'Autism Spectrum',
    'Or, in your own words:': 'Self-described',
    'Prefer not to say': 'Unknown'
}

multi_select_cols = [
    "Gender", "Sexuality", "Ethnicity", 
    "Accessibility", "MentalHealth"
]
multi_select_normalized = [
     "Gender_Clean", "Sexuality_Clean", "Ethnicity_Clean", 
    "Accessibility_Status", "Mental_Health_Status"
]
multi_select_maps = [
    gender_map,       
    sexuality_map,     
    ethnicity_map,     
    accessibility_map, 
    mental_health_map
]
normalize_categorical_columns_non_exploding(Survey_2021_df_cleaned, multi_select_cols, multi_select_normalized, multi_select_maps)

Gender_Clean
Man                   74817
Woman                  4120
Unknown                2595
Non-binary / GNC       1103
Diverse / Multiple      804
Name: count, dtype: int64
Sexuality_Clean
Straight              61094
Unknown               14856
Bisexual               2879
Diverse / Multiple     1609
Gay or Lesbian         1367
Self-described         1258
Queer                   376
Name: count, dtype: int64
Ethnicity_Clean
White                   42671
Unknown                  9177
South Asian              8328
Diverse / Multiple       5690
Hispanic/Latino          3585
Southeast Asian          3224
Middle Eastern           2985
East Asian               2947
Black                    2085
Self-described           2014
Multiracial/Biracial      650
Indigenous                 83
Name: count, dtype: int64
Accessibility_Status
None                           72725
Unknown                         7754
Visual Impairment               1030
Self-described                   842
Hearing Impairment               442
Diverse / Multiple               298
Mobility (Walking/Standing)      188
Mobility (Typing)                160
Name: count, dtype: int64
Mental_Health_Status
None                  56459
Unknown               10451
Diverse / Multiple     6032
ADHD/Concentration     3059
Anxiety                2840
Mood/Emotional         2324
Autism Spectrum        1224
Self-described         1050
Name: count, dtype: int64

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Survey_Length,Survey_Ease,USA_State,Know_Other_Community,Compensation_Frequency,Gender_Clean,Sexuality_Clean,Ethnicity_Clean,Accessibility_Status,Mental_Health_Status
0,1,I am a developer by profession,Freelance,Slovakia,NaN,Not Available or Applicable,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,Appropriate,Easy,Not Available or Applicable,No,Monthly,Man,Straight,White,None,None
1,2,I am a student who is learning to code,Student,Netherlands,NaN,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,Appropriate,Easy,Not Available or Applicable,No,Not Available or Applicable,Man,Straight,White,None,None
2,3,"I am not primarily a developer, but I write co...",Student,Russian Federation,NaN,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,Appropriate,Easy,Not Available or Applicable,Yes,Not Available or Applicable,Man,Unknown,Unknown,None,None
3,4,I am a developer by profession,Employed,Austria,NaN,Not Available or Applicable,"MasterΓÇÖs degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,Appropriate,Neutral,Not Available or Applicable,No,Monthly,Man,Straight,White,Hearing Impairment,Unknown
4,5,I am a developer by profession,Freelance,United Kingdom of Great Britain and Northern I...,NaN,England,"MasterΓÇÖs degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,Appropriate,Easy,Not Available or Applicable,No,Not Available or Applicable,Man,Unknown,White,None,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,83435,I am a developer by profession,Employed,United States of America,Texas,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,...,Appropriate,Easy,Texas,No,Yearly,Man,Straight,White,None,ADHD/Concentration
83435,83436,I am a developer by profession,Freelance,Benin,NaN,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,...,Appropriate,Easy,Not Available or Applicable,No,Monthly,Man,Straight,Black,None,None
83436,83437,I am a developer by profession,Employed,United States of America,New Jersey,Not Available or Applicable,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,...,Appropriate,Neutral,New Jersey,No,Weekly,Man,Unknown,White,None,None
83437,83438,I am a developer by profession,Employed,Canada,NaN,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,...,Appropriate,Neutral,Not Available or Applicable,No,Monthly,Man,Straight,White,None,Mood/Emotional
83438,83439,I am a developer by profession,Employed,Brazil,NaN,Not Available or Applicable,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,...,Appropriate,Easy,Not Available or Applicable,No,Monthly,Man,Straight,Hispanic/Latino,None,None

In [22]:
# Mormalization of categorical columns :  we will create a mapping to group similar roles and responses together, reducing the number of unique values while preserving the overall meaning.

dev_type_map = {
    'Developer, full-stack': 'Full-stack', 'Developer, back-end': 'Back-end',
    'Developer, front-end': 'Front-end', 'Developer, mobile': 'Mobile',
    'Developer, desktop or enterprise applications': 'Desktop/Enterprise',
    'Engineer, data': 'Data Engineer', 'Data scientist or machine learning specialist': 'Data Scientist/ML',
    'Data or business analyst': 'Data/BI Analyst', 'DevOps specialist': 'DevOps',
    'Engineer, site reliability': 'SRE', 'Engineering manager': 'Engineering Manager',
    'Senior Executive (C-Suite, VP, etc.)': 'Executive', 'System administrator': 'SysAdmin',
    'Database administrator': 'DBA', 'Developer, game or graphics': 'Game/Graphics',
    'Developer, embedded applications or devices': 'Embedded/IoT', 'Developer, QA or test': 'QA/Testing',
    'Academic researcher': 'Researcher', 'Scientist': 'Scientist', 'Student': 'Student',
    'Educator': 'Educator', 'Designer': 'Designer', 'Product manager': 'Product Manager',
    'Marketing or sales professional': 'Marketing/Sales', 'Other (please specify):': 'Other'
}

stuck_map = {
    'Google it': 'Search (Google)', 'Visit Stack Overflow': 'Community (Stack Overflow)',
    'Visit another developer community (please name):': 'Community (Other)',
    'Watch help / tutorial videos': 'Self-Paced Learning', 'Go for a walk or other physical activity': 'Physical Break',
    'Meditate': 'Mental Break', 'Play games': 'Mental Break', 'Do other work and come back later': 'Context Switch',
    'Call a coworker or friend': 'Social Support', 'Panic': 'Emotional Response', 'Other (please specify):': 'Other'
}
learn_code_map = {
    'School': 'Academic (Degree)',
    'Coding Bootcamp': 'Bootcamp',
    'Online Courses or Certification': 'Online Certifications',
    'Other online resources (ex: videos, blogs, etc)': 'Digital Self-Taught',
    'Books / Physical media': 'Physical Media',
    'Online Forum': 'Community/Forums',
    'Colleague': 'Professional Network',
    'Friend or family member': 'Social/Family',
    'Other (please specify):': 'Other'
}
tech_stack_cols = [
    'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 
    'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 
    'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 
    'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 
    'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith', 
    'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith', 
    'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith'
]
manual_mapping_cols = [
    'DevType', 'NEWStuck'
]
all_target_cols = manual_mapping_cols + tech_stack_cols
manual_maps = {
    'DevType': dev_type_map,
    'NEWStuck': stuck_map,
    'LearnCode':learn_code_map
}

bridge_results = {}
target_names = [
    col + '_Clean' 
    for col in all_target_cols
]
maps_to_use = [
    manual_maps.get(col) 
    for col in all_target_cols
]


bridge_results = normalize_categorical_columns_exploding(
    Survey_2021_df_cleaned, 
    all_target_cols, 
    target_names, 
    maps_to_use
)

--- Distribution for DevType_Clean ---
DevType_Clean
Full-stack             32891
Back-end               29071
Front-end              18231
Other/Unknown          16955
Desktop/Enterprise     11036
Mobile                  9800
DevOps                  7058
SysAdmin                6079
DBA                     5655
Designer                4611
Embedded/IoT            4598
Data Scientist/ML       4273
Student                 4187
Data Engineer           4176
Engineering Manager     3810
Data/BI Analyst         3792
QA/Testing              3611
Other                   3545
Product Manager         3074
Researcher              2899
SRE                     2448
Educator                2369
Game/Graphics           2112
Executive               2103
Scientist               2015
Marketing/Sales          638
Name: count, dtype: int64
------------------------------
--- Distribution for NEWStuck_Clean ---
NEWStuck_Clean
Search (Google)               74491
Community (Stack Overflow)    66410
Context Switch                39871
Self-Paced Learning           36181
Social Support                32805
Physical Break                30760
Mental Break                  19937
Emotional Response             9962
Community (Other)              6577
Other                          5812
Other/Unknown                   387
Name: count, dtype: int64
------------------------------
--- Distribution for LanguageHaveWorkedWith_Clean ---
LanguageHaveWorkedWith_Clean
JavaScript       53587
HTML/CSS         46259
Python           39792
SQL              38835
Java             29162
Node.js          27975
TypeScript       24909
C#               22984
Bash/Shell       22385
C++              20057
PHP              18130
C                17329
PowerShell        8871
Go                7879
Kotlin            6866
Rust              5799
Ruby              5569
Dart              4965
Assembly          4632
Swift             4204
R                 4185
VBA               3847
Matlab            3846
Groovy            2479
Objective-C       2310
Scala             2148
Perl              2028
Haskell           1749
Delphi            1731
Clojure           1552
Elixir            1438
LISP              1096
Other/Unknown     1082
Julia             1068
F#                 804
Erlang             651
APL                536
Crystal            466
COBOL              437
Name: count, dtype: int64
------------------------------
--- Distribution for LanguageWantToWorkWith_Clean ---
LanguageWantToWorkWith_Clean
JavaScript       37008
Python           34929
HTML/CSS         29353
TypeScript       26905
SQL              26631
Node.js          24100
C#               17999
Java             17222
Rust             15865
Go               15788
C++              15249
Bash/Shell       14043
Kotlin           10691
C                 9702
PHP               8852
Dart              7018
Other/Unknown     6618
Swift             6353
Ruby              4942
PowerShell        4896
R                 4015
Assembly          3578
Haskell           3453
Elixir            3374
Scala             3165
Julia             2445
Clojure           2413
F#                2157
Matlab            1562
LISP              1513
Objective-C       1400
Erlang            1379
Groovy            1177
Perl              1175
VBA               1069
Delphi             975
Crystal            790
APL                568
COBOL              309
Name: count, dtype: int64
------------------------------
--- Distribution for DatabaseHaveWorkedWith_Clean ---
DatabaseHaveWorkedWith_Clean
MySQL                   35289
PostgreSQL              28424
SQLite                  22634
MongoDB                 19479
Microsoft SQL Server    18896
Redis                   14552
Other/Unknown           13893
MariaDB                 12088
Firebase                11373
Elasticsearch            9331
Oracle                   8868
DynamoDB                 5137
Cassandra                1873
IBM DB2                  1438
Couchbase                1106
Name: count, dtype: int64
------------------------------
--- Distribution for DatabaseWantToWorkWith_Clean ---
DatabaseWantToWorkWith_Clean
PostgreSQL              27082
Other/Unknown           25140
MySQL                   20307
MongoDB                 20131
Redis                   17212
SQLite                  15381
Elasticsearch           11644
Microsoft SQL Server    11394
Firebase                10776
MariaDB                  8176
DynamoDB                 6039
Oracle                   4557
Cassandra                4227
Couchbase                1670
IBM DB2                   678
Name: count, dtype: int64
------------------------------
--- Distribution for PlatformHaveWorkedWith_Clean ---
PlatformHaveWorkedWith_Clean
Other/Unknown                  31304
AWS                            29138
Google Cloud Platform          16687
Microsoft Azure                16540
Heroku                         12897
DigitalOcean                    9495
IBM Cloud or Watson             1373
Oracle Cloud Infrastructure     1014
Name: count, dtype: int64
------------------------------
--- Distribution for PlatformWantToWorkWith_Clean ---
PlatformWantToWorkWith_Clean
Other/Unknown                  41820
AWS                            26295
Google Cloud Platform          16228
Microsoft Azure                15096
DigitalOcean                    8674
Heroku                          8182
IBM Cloud or Watson             1768
Oracle Cloud Infrastructure     1398
Name: count, dtype: int64
------------------------------
--- Distribution for WebframeHaveWorkedWith_Clean ---
WebframeHaveWorkedWith_Clean
React.js         25296
Other/Unknown    21732
jQuery           21693
Express          15010
Angular          14471
Vue.js           11954
ASP.NET Core     11404
Flask            10174
ASP.NET           9918
Django            9446
Spring            9177
Angular.js        7242
Laravel           6377
Ruby on Rails     4438
Gatsby            2501
FastAPI           2447
Symfony           2427
Svelte            1735
Drupal            1508
Name: count, dtype: int64
------------------------------
--- Distribution for WebframeWantToWorkWith_Clean ---
WebframeWantToWorkWith_Clean
Other/Unknown    31344
React.js         25718
Vue.js           15784
Express          11885
Angular          11533
ASP.NET Core     10454
Django            9112
jQuery            8487
Flask             7594
Spring            7229
Svelte            5235
Laravel           4734
ASP.NET           4488
Angular.js        4293
Ruby on Rails     4249
FastAPI           3989
Gatsby            2830
Symfony           1786
Drupal             653
Name: count, dtype: int64
------------------------------
--- Distribution for MiscTechHaveWorkedWith_Clean ---
MiscTechHaveWorkedWith_Clean
Other/Unknown         36384
.NET Framework        16620
NumPy                 16445
.NET Core / .NET 5    15310
Pandas                13664
TensorFlow             8034
React Native           7051
Flutter                6586
Keras                  4930
Qt                     4812
Torch/PyTorch          4808
Cordova                3491
Apache Spark           2833
Hadoop                 2155
Name: count, dtype: int64
------------------------------
--- Distribution for MiscTechWantToWorkWith_Clean ---
MiscTechWantToWorkWith_Clean
Other/Unknown         45418
.NET Core / .NET 5    13630
NumPy                 12773
TensorFlow            11879
Pandas                10863
Flutter                9212
React Native           8621
Torch/PyTorch          7977
.NET Framework         7761
Keras                  5190
Qt                     3478
Apache Spark           3453
Hadoop                 2802
Cordova                1475
Name: count, dtype: int64
------------------------------
--- Distribution for ToolsTechHaveWorkedWith_Clean ---
ToolsTechHaveWorkedWith_Clean
Git              68171
Docker           35644
Yarn             12937
Kubernetes       12115
Other/Unknown    10902
Unity 3D          7206
Ansible           5607
Terraform         5442
Xamarin           2844
Unreal Engine     2339
Puppet            1313
Deno              1027
Chef               982
Flow               929
Pulumi             368
Name: count, dtype: int64
------------------------------
--- Distribution for ToolsTechWantToWorkWith_Clean ---
ToolsTechWantToWorkWith_Clean
Git              58308
Docker           37870
Kubernetes       21977
Other/Unknown    17959
Yarn              9936
Unity 3D          8285
Terraform         7756
Ansible           5876
Unreal Engine     5563
Deno              4773
Xamarin           2977
Puppet            1428
Chef              1119
Flow               974
Pulumi             901
Name: count, dtype: int64
------------------------------
--- Distribution for NEWCollabToolsHaveWorkedWith_Clean ---
NEWCollabToolsHaveWorkedWith_Clean
Visual Studio Code    58026
Visual Studio         26970
Notepad++             24262
IntelliJ              23467
Vim                   19752
Android Studio        18141
Sublime Text          16714
PyCharm               15755
Eclipse               12955
Atom                  10564
IPython/Jupyter       10310
Xcode                  9040
Webstorm               6564
PHPStorm               6096
NetBeans               5839
Emacs                  4327
Neovim                 4071
Rider                  3255
RStudio                3200
Other/Unknown          2205
RubyMine               1219
TextMate                678
Name: count, dtype: int64
------------------------------
--- Distribution for NEWCollabToolsWantToWorkWith_Clean ---
NEWCollabToolsWantToWorkWith_Clean
Visual Studio Code    48360
IntelliJ              17777
Visual Studio         17580
Vim                   15620
Notepad++             13916
Android Studio        11916
PyCharm               11343
Other/Unknown         10417
Sublime Text           9326
IPython/Jupyter        7931
Xcode                  7596
Webstorm               5311
Eclipse                4592
Neovim                 4293
Atom                   4224
PHPStorm               4044
Emacs                  3736
Rider                  3210
RStudio                2095
NetBeans               1652
RubyMine               1021
TextMate                396
Name: count, dtype: int64
------------------------------

In [23]:
# Cleaning the year Columns
experience_cols = ['YearsCode', 'YearsCodePro']
Survey_2021_df_cleaned = clean_years_columns(Survey_2021_df_cleaned, experience_cols)

In [24]:
# Cleaning the Currency column and Salary Columns :  we will extract the currency code from the 'Currency' column, which may contain additional information such as the currency name or symbol. We will then convert the salary columns to numeric values, handling any non-numeric entries appropriately. Finally, we will fill missing values and remove outliers from the salary columns to ensure a more accurate analysis of compensation data.
col = 'Currency'

Survey_2021_df_cleaned[col] = Survey_2021_df_cleaned[col].str.split().str[0]

nan_replacer_cols = ['Currency']
cleaned_nan_cols = ['Currency_Code']

Survey_2021_df_cleaned = normalize_na_replacer_columns(
    Survey_2021_df_cleaned,
    nan_replacer_cols, 
    cleaned_nan_cols,
    replacer_value="Not Available"
)

numeric_target_cols = ['CompTotal', 'ConvertedCompYearly']
Survey_2021_df_cleaned = string_to_numeric(Survey_2021_df_cleaned, numeric_target_cols)

fill_na_and_remove_outlier_percentaile_method(Survey_2021_df_cleaned, 'ConvertedCompYearly', 0.01, 0.95)
fill_na_and_remove_outlier_percentaile_method(Survey_2021_df_cleaned, 'CompTotal', 0.01, 0.95)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Survey_Ease,USA_State,Know_Other_Community,Compensation_Frequency,Gender_Clean,Sexuality_Clean,Ethnicity_Clean,Accessibility_Status,Mental_Health_Status,Currency_Code
0,1,I am a developer by profession,Freelance,Slovakia,NaN,Not Available or Applicable,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,0,...,Easy,Not Available or Applicable,No,Monthly,Man,Straight,White,None,None,EUR
1,2,I am a student who is learning to code,Student,Netherlands,NaN,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,Easy,Not Available or Applicable,No,Not Available or Applicable,Man,Straight,White,None,None,Not Available
2,3,"I am not primarily a developer, but I write co...",Student,Russian Federation,NaN,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",0,...,Easy,Not Available or Applicable,Yes,Not Available or Applicable,Man,Unknown,Unknown,None,None,Not Available
3,4,I am a developer by profession,Employed,Austria,NaN,Not Available or Applicable,"MasterΓÇÖs degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,0,...,Neutral,Not Available or Applicable,No,Monthly,Man,Straight,White,Hearing Impairment,Unknown,EUR
4,5,I am a developer by profession,Freelance,United Kingdom of Great Britain and Northern I...,NaN,England,"MasterΓÇÖs degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,Easy,Not Available or Applicable,No,Not Available or Applicable,Man,Unknown,White,None,Unknown,GBP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,83435,I am a developer by profession,Employed,United States of America,Texas,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,...,Easy,Texas,No,Yearly,Man,Straight,White,None,ADHD/Concentration,USD
83435,83436,I am a developer by profession,Freelance,Benin,NaN,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,...,Easy,Not Available or Applicable,No,Monthly,Man,Straight,Black,None,None,XOF
83436,83437,I am a developer by profession,Employed,United States of America,New Jersey,Not Available or Applicable,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,...,Neutral,New Jersey,No,Weekly,Man,Unknown,White,None,None,USD
83437,83438,I am a developer by profession,Employed,Canada,NaN,Not Available or Applicable,"BachelorΓÇÖs degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,...,Neutral,Not Available or Applicable,No,Monthly,Man,Straight,White,None,Mood/Emotional,CAD
83438,83439,I am a developer by profession,Employed,Brazil,NaN,Not Available or Applicable,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,...,Easy,Not Available or Applicable,No,Monthly,Man,Straight,Hispanic/Latino,None,None,BRL

In [27]:
# 1. Original columns that now have "Clean" versions
raw_redundant_cols = [
    'Employment', 'EdLevel', 'Age1stCode', 'LearnCode', 'OpSys', 
    'OrgSize', 'Trans', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 
    'SOComm', 'NEWSOSites', 'SurveyLength', 'SurveyEase', 'US_State', 
    'NEWOtherComms', 'CompFreq', 'Currency', 'Gender', 'Sexuality', 
    'Ethnicity', 'Accessibility', 'MentalHealth', 'Age', 'UK_Country'
]

# 2. Raw multi-select strings (already exploded into bridge_results)
multi_select_strings = [
    'DevType', 'NEWStuck', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
    'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
    'PlatformWantToWorkWith', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
    'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
    'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith'
]

# Combine and drop
total_drop_list = list(set(raw_redundant_cols + multi_select_strings))

Survey_2021_df_cleaned.drop(columns=total_drop_list, inplace=True, errors='ignore')

# Verification
print(f"Final Column Count: {len(Survey_2021_df_cleaned.columns)}")
print(Survey_2021_df_cleaned.columns.tolist())

Final Column Count: 29
['ResponseId', 'MainBranch', 'Country', 'YearsCode', 'YearsCodePro', 'CompTotal', 'ConvertedCompYearly', 'SurveyYear', 'Education_Level', 'AgeCode', 'OperatingSystem', 'Organization_Size', 'TransGender', 'StackOverflow_Visit_Frequency', 'StackOverflow_Account_exists', 'StackOverflow_Participation_Frequency', 'StackOverflow_Community_Experience', 'NewStackOverflow_Sites', 'Survey_Length', 'Survey_Ease', 'USA_State', 'Know_Other_Community', 'Compensation_Frequency', 'Gender_Clean', 'Sexuality_Clean', 'Ethnicity_Clean', 'Accessibility_Status', 'Mental_Health_Status', 'Currency_Code']

In [ ]:
# Writing back to SQL
# Central Fact Table 2021
write_to_sql(df=Survey_2021_df_cleaned,schema='Silver', table_name='Survey_2021', engine=engine)
write_to_sql

# Bridge Tables for Tech Stack and Manual Mapping Columns
for table_name, bridge_df in bridge_results.items():
    write_to_sql(df=bridge_df,schema='Silver', table_name=f"Bridge_{table_name}", engine=engine)

c:\Users\Ayush\Git Repo\Stack-Over-Flow-Survey-Data-Engineering-Project\Data Warehouse\Silver Layer\utils\sql_connector.py:39: FutureWarning: Starting with pandas version 3.0 all arguments of to_sql except for the arguments 'name' and 'con' will be keyword-only.
  df.to_sql(table_name, engine,schema, if_exists='replace', index=False )

DataFrame written to SQL table 'Silver.Survey_2021' successfully.
DataFrame written to SQL table 'Silver.Bridge_DevType_Clean' successfully.
DataFrame written to SQL table 'Silver.Bridge_NEWStuck_Clean' successfully.